// USERJOBS MODULE
export const MOVIE_INFORMATIONS_REQUEST = 'MOVIE_INFORMATIONS_REQUEST'
export const MOVIE_INFORMATIONS_SUCCESS = 'MOVIE_INFORMATIONS_SUCCESS'
export const MOVIE_INFORMATIONS_ERROR = 'MOVIE_INFORMATIONS_ERROR'
