// USERJOBS MODULE
export const RESEARCH_MOVIES_REQUEST = 'RESEARCH_MOVIES_REQUEST'
export const RESEARCH_MOVIES_SUCCESS = 'RESEARCH_MOVIES_SUCCESS'
export const RESEARCH_MOVIES_ERROR = 'RESEARCH_MOVIES_ERROR'
